service: blog-generator

provider:
  name: aws
  runtime: python3.6
  region: eu-west-3
  memorySize: 256

functions:
  generateBlog:
    handler: handler.generateBlog
    events:
      - http:
          path: /{language}
          method: get
          cors: true
          request:
            parameters:
              paths:
                language: true

plugins:
  - serverless-python-requirements